# Generated by Django 4.1.7 on 2023-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=220)),
                ('price', models.PositiveBigIntegerField()),
                ('display', models.CharField(default='lcd', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=220)),
                ('rating', models.CharField(max_length=290)),
            ],
        ),
    ]
