# Generated by Django 4.1.7 on 2023-04-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=200)),
                ('runtime', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
